# Generated by Django 4.2.5 on 2023-11-21 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='static/images/post/post_default_image.png', upload_to='blog/images/post'),
        ),
    ]
