# Generated by Django 4.2.5 on 2023-11-23 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='static/post_default_image.png', upload_to='blog/posts'),
        ),
    ]
