# Generated by Django 4.2.5 on 2023-11-23 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='blog/static/images/posts/post_default_image.png', upload_to='blog/static/images/posts/'),
        ),
    ]
