# Generated by Django 4.2.5 on 2023-11-23 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='blog/static/images/posts/post_default_thumbnail.png', upload_to='blog/static/images/posts/'),
        ),
    ]
