# Generated by Django 4.2.5 on 2023-11-23 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_post_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='static/images/post_default_thumbnail.png', upload_to='blog/static/images/thumbnails/'),
        ),
    ]
